export const REPORT_CONFIGS = {
  client_roster: {
    title: "Client Roster",
    description: "Comprehensive view of client care rosters and assigned staff.",
    categoryOptionsText: "Back to Roster Options",
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "groupBy", label: "GROUP BY *", type: "select", placeholder: "Client" },
      { id: "requirements", label: "REQUIREMENTS *", type: "select", placeholder: "All requirements" },
      { id: "globalTasks", label: "GLOBAL TASKS *", type: "select", placeholder: "All tasks" },
      { id: "dateRange", label: "SHOW ROSTER FOR *", type: "dateRange" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DATE", "TIME (DURATION) & STATUS", "CARER(S)"],
    data: [
      {
        client: "Harshavardini Sureshkumar",
        date: "Thu 9 Apr",
        time: "14:30 - 16:30 (2 hours) **CANCELLED**",
        carers: "Carer required",
      },
      {
        client: "Kamal Henry",
        date: "Thu 9 Apr",
        time: "17:00 - 20:00 (3 hours)",
        carers: "Abdulmumin Yusuf, Ruth Omoregie",
      },
      {
        client: "Nathan Oladoyinbo",
        date: "Thu 9 Apr",
        time: "13:30 - 16:00 (2 hours, 30 minutes)",
        carers: "Ruth Omoregie",
      },
      {
        client: "Nuwairah wasif",
        date: "Thu 9 Apr",
        time: "13:00 - 16:00 (3 hours)",
        carers: "Adigun Adenike comfort",
      },
    ],
  },
  client_schedule: {
    title: "Client Schedule",
    description: "Detailed daily and weekly schedules for individual clients.",
    categoryOptionsText: "Back to Roster Options",
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "cancelled", label: "CANCELLED *", type: "select", placeholder: "Any" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DAY", "START TIME", "END TIME", "DURATION", "CARER", "CANCELLED"],
    data: [
      {
        client: "Alice Pucacco",
        day: "Sunday",
        startTime: "14:00",
        endTime: "18:00",
        duration: "4 hours",
        carer: "Sorupa Akter",
        cancelled: "No",
      },
      {
        client: "Harshavardini Sureshkumar",
        day: "Monday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "Tuesday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
    ],
  },
  unassigned_appts: {
    title: "Unassigned Appointments",
    description: "Track and manage client appointments lacking assigned carers.",
    categoryOptionsText: "Back to Roster Options",
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "dateRange", label: "SHOW APPOINTMENTS FOR *", type: "dateRange" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DAY", "TIME", "CARER", "VIEW RECOMMENDED CARER"],
    data: [
      {
        client: "Alice Pucacco",
        day: "Thu 9 Apr",
        time: "14:00 - 18:00",
        carer: "Unassigned",
        recommended: "View Recommendations",
      },
      {
        client: "John Marston",
        day: "Fri 10 Apr",
        time: "09:00 - 11:00",
        carer: "Unassigned",
        recommended: "View Recommendations",
      },
    ],
  },
  client_diary: {
    title: "Client Diary",
    description: "Detailed daily logs, notes, and observations for individual clients.",
    categoryOptionsText: "Back to Diary Options",
    filters: [
      { id: "dateFrom", label: "SHOW DIARY ENTRIES FROM *", type: "date" },
      { id: "dateUntil", label: "UNTIL *", type: "date" },
      { id: "incidentTypes", label: "INCIDENT TYPES *", type: "select", placeholder: "All types" },
      { id: "usersInvolved", label: "USERS INVOLVED *", type: "select", placeholder: "All clients" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["DISPLAY FROM", "DISPLAY UNTIL", "ENTRY OCCURRED", "INCIDENT TYPE", "CARERS INVOLVED", "CLIENTS INVOLVED", "DIARY ENTRY", "DIARY LINK"],
    data: [
      {
        displayFrom: "30/03/2026",
        displayUntil: "12/04/2026",
        entryOccurred: "30/03/2026",
        incidentType: "Note",
        carersInvolved: "",
        clientsInvolved: "Tania JAVEED",
        diaryEntry: "school holiday week",
        diaryLink: "Edit entry",
      },
      {
        displayFrom: "06/04/2026",
        displayUntil: "12/04/2026",
        entryOccurred: "06/04/2026",
        incidentType: "Note",
        carersInvolved: "",
        clientsInvolved: "Nathan Oladoyinbo",
        diaryEntry: "school holiday week",
        diaryLink: "Edit entry",
      },
    ],
  },
};
