export const REPORT_CONFIGS = {
  respite: {
    title: "Respite",
    description: "Track respite care hours and usage.",
    category: "CLIENT",
    categoryOptionsText: "Back to Library",
    categoryBackPath: "/reports",
    filtersInline: true,
    filters: [
      { id: "clients", label: "CLIENTS *", type: "select", placeholder: "All clients" },
      { id: "dateRange", label: "SHOW RESPITE FROM *", type: "dateRangeLabeled" },
      { id: "respiteType", label: "RESPITE TYPE *", type: "select", placeholder: "All types" },
    ],
    columns: ["CLIENT", "START", "END", "TYPE", "NOTES"],
    data: [
      {
        client: "Alice Pucacco",
        start: "10/04/2026 09:00",
        end: "10/04/2026 17:00",
        type: "In-Home",
        notes: "Family requested day respite.",
      },
      {
        client: "John Marston",
        start: "11/04/2026 10:00",
        end: "12/04/2026 10:00",
        type: "Overnight",
        notes: "Weekend respite care.",
      },
    ],
  },
  care_plans: {
    title: "Care Plans",
    description: "View and manage active care plans for clients.",
    category: "CLIENT",
    categoryOptionsText: "Back to Checklist Options",
    filtersInline: true,
    filters: [
      { id: "client", label: "CLIENTS *", type: "select", placeholder: "All clients" },
      { id: "renewalDate", label: "SHOW CARE PLAN RENEWALS REQUIRED BY *", type: "date", placeholder: "10/10/2026" },
    ],
    columns: ["CLIENT", "ASSESSED DATE", "ASSESSED BY", "REVIEW DATE"],
    data: [
      { client: "Zara Campbell", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Kamal Henry", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Nuwwlrah Wesif", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Tania JAVEED", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Temiloluwa Enifeni", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Samuel Campbell", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Saahara Robinshan", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Nathan Oladoyinbo", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Harshavardini Sureshkumar", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
      { client: "Alice Pucacco", assessedDate: "Never provided", assessedBy: "Unknown", reviewDate: "Unknown" },
    ],
  },
  outstanding_checklist: {
    title: "Outstanding Checklist Items",
    description: "Track incomplete or pending checklist tasks.",
    category: "CLIENT",
    categoryOptionsText: "Back to Checklist Options",
    filtersInline: true,
    filters: [
      { id: "client", label: "CLIENTS *", type: "select", placeholder: "All clients" },
      { id: "checklistItem", label: "CHECKLIST ITEM *", type: "select", placeholder: "All types" },
      { id: "requiredBy", label: "SHOW ITEMS REQUIRED BY *", type: "date", placeholder: "05/10/2026" },
    ],
    columns: ["CLIENT", "CHECKLIST ITEM", "REQUIRED BY"],
    data: [
      { client: "Alice Pucacco", checklistItem: "Monthly Review", requiredBy: "10/05/2026" },
      { client: "John Marston", checklistItem: "Risk Assessment Update", requiredBy: "12/05/2026" },
    ],
  },
  checklist_history: {
    title: "Checklist History",
    description: "Comprehensive log of all completed checklist items.",
    category: "CLIENT",
    categoryOptionsText: "Back to Checklist Options",
    filtersInline: true,
    filters: [
      { id: "client", label: "CLIENTS *", type: "select", placeholder: "All clients" },
      { id: "checklistItem", label: "CHECKLIST ITEM *", type: "select", placeholder: "All types" },
    ],
    columns: ["CLIENT", "CHECKLIST ITEM", "DOCUMENT", "DATE LAST TAKEN", "REFRESH REQUIRED BY", "MODIFIED BY", "MODIFIED DATE"],
    data: [
      {
        client: "Alice Pucacco",
        checklistItem: "Monthly Review",
        document: "Review_April.pdf",
        dateLastTaken: "10/04/2026",
        refreshRequiredBy: "10/05/2026",
        modifiedBy: "System",
        modifiedDate: "10/04/2026",
      },
      {
        client: "John Marston",
        checklistItem: "Risk Assessment Update",
        document: "Risk_Assessment_Q2.pdf",
        dateLastTaken: "12/04/2026",
        refreshRequiredBy: "12/05/2026",
        modifiedBy: "Admin",
        modifiedDate: "12/04/2026",
      },
    ],
  },
  checklist_history_by_date: {
    title: "Checklist History by Date",
    description: "View checklist completion records organized by date.",
    category: "CLIENT",
    categoryOptionsText: "Back to Checklist Options",
    filtersInline: true,
    filters: [
      { id: "client", label: "CLIENTS *", type: "select", placeholder: "All clients" },
      { id: "checklistItem", label: "CHECKLIST ITEM *", type: "select", placeholder: "All types" },
      { id: "dateRange", label: "SHOW ITEMS BETWEEN *", type: "dateRangeAnd" },
    ],
    columns: ["CLIENT", "CHECKLIST ITEM", "DOCUMENT", "DATE LAST TAKEN", "REFRESH REQUIRED BY", "MODIFIED BY", "MODIFIED DATE"],
    data: [
      {
        client: "Alice Pucacco",
        checklistItem: "Monthly Review",
        document: "Review_April.pdf",
        dateLastTaken: "10/04/2026",
        refreshRequiredBy: "10/05/2026",
        modifiedBy: "System",
        modifiedDate: "10/04/2026",
      },
      {
        client: "John Marston",
        checklistItem: "Risk Assessment Update",
        document: "Risk_Assesment_Q2.pdf",
        dateLastTaken: "12/04/2026",
        refreshRequiredBy: "12/05/2026",
        modifiedBy: "Admin",
        modifiedDate: "12/04/2026",
      },
    ],
  },
  client_roster: {
    title: "Client Roster",
    description: "Comprehensive view of client care rosters and assigned staff.",
    categoryOptionsText: "Back to Roster Options",
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "groupBy", label: "GROUP BY *", type: "dropdown", placeholder: "Client" },
      { id: "requirements", label: "REQUIREMENTS *", type: "select", placeholder: "All requirements" },
      { id: "globalTasks", label: "GLOBAL TASKS *", type: "select", placeholder: "All tasks" },
      { id: "dateRange", label: "SHOW ROSTER FOR *", type: "dateRange" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DATE", "TIME (DURATION) & STATUS", "CARER(S)"],
    data: [
      {
        client: "Harshavardini Sureshkumar",
        date: "Thu 9 Apr",
        time: "14:30 - 16:30 (2 hours) **CANCELLED**",
        carers: "Carer required",
      },
      {
        client: "Kamal Henry",
        date: "Thu 9 Apr",
        time: "17:00 - 20:00 (3 hours)",
        carers: "Abdulmumin Yusuf, Ruth Omoregie",
      },
      {
        client: "Nathan Oladoyinbo",
        date: "Thu 9 Apr",
        time: "13:30 - 16:00 (2 hours, 30 minutes)",
        carers: "Ruth Omoregie",
      },
      {
        client: "Nuwairah wasif",
        date: "Thu 9 Apr",
        time: "13:00 - 16:00 (3 hours)",
        carers: "Adigun Adenike comfort",
      },
      {
        client: "Temiloluwa Enifeni",
        date: "Thu 9 Apr",
        time: "12:30 - 16:00 (3 hours, 30 minutes)",
        carers: "Abdulmumin Yusuf, Ayodeji ogunjana",
      },
      {
        client: "Zara Campbell",
        date: "Thu 9 Apr",
        time: "09:30 - 11:30 (2 hours)",
        carers: "Ruth Omoregie",
      },
    ],
  },
  client_schedule: {
    title: "Client Schedule",
    description: "Detailed daily and weekly schedules for individual clients.",
    categoryOptionsText: "Back to Roster Options",
    filtersInline: true,
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "cancelled", label: "CANCELLED *", type: "dropdown", placeholder: "Any" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DAY", "START TIME", "END TIME", "DURATION", "CARER", "CANCELLED"],
    data: [
      {
        client: "Alice Pucacco",
        day: "Sunday",
        startTime: "14:00",
        endTime: "18:00",
        duration: "4 hours",
        carer: "Sorupa Akter",
        cancelled: "No",
      },
      {
        client: "Harshavardini Sureshkumar",
        day: "Monday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "",
        startTime: "15:10",
        endTime: "17:40",
        duration: "2 hours, 30 minutes",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "Tuesday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "",
        startTime: "15:10",
        endTime: "17:40",
        duration: "2 hours, 30 minutes",
        carer: "Yogabrindha Kanagaraj",
        cancelled: "No",
      },
      {
        client: "",
        day: "Wednesday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "",
        startTime: "15:10",
        endTime: "17:40",
        duration: "2 hours, 30 minutes",
        carer: "Yogabrindha Kanagaraj",
        cancelled: "No",
      },
      {
        client: "",
        day: "Thursday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "",
        startTime: "15:10",
        endTime: "17:40",
        duration: "2 hours, 30 minutes",
        carer: "Yogabrindha Kanagaraj",
        cancelled: "No",
      },
      {
        client: "",
        day: "Friday",
        startTime: "07:30",
        endTime: "09:30",
        duration: "2 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
      {
        client: "",
        day: "",
        startTime: "15:10",
        endTime: "17:40",
        duration: "2 hours, 30 minutes",
        carer: "Ruth Omoregie",
        cancelled: "No",
      },
      {
        client: "",
        day: "Saturday",
        startTime: "09:00",
        endTime: "14:00",
        duration: "5 hours",
        carer: "Priya Sasikumar",
        cancelled: "No",
      },
    ],
  },
  unassigned_appts: {
    title: "Unassigned Appointments",
    description: "Track and manage client appointments lacking assigned carers.",
    categoryOptionsText: "Back to Roster Options",
    filtersInline: true,
    filters: [
      { id: "name", label: "NAME *", type: "select", placeholder: "All clients" },
      { id: "dateRange", label: "SHOW APPOINTMENTS FOR *", type: "dateRange" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["CLIENT", "DAY", "TIME", "CARER", "VIEW RECOMMENDED CARER"],
    data: [
      {
        client: "Alice Pucacco",
        day: "Thu 9 Apr",
        time: "14:00 - 18:00",
        carer: "Unassigned",
        recommended: "View Recommendations",
      },
      {
        client: "John Marston",
        day: "Fri 10 Apr",
        time: "09:00 - 11:00",
        carer: "Unassigned",
        recommended: "View Recommendations",
      },
    ],
  },
  client_diary: {
    title: "Client Diary",
    description: "Detailed daily logs, notes, and observations for individual clients.",
    categoryOptionsText: "Back to Diary Options",
    filtersInline: true,
    filters: [
      { id: "dateFrom", label: "SHOW DIARY ENTRIES FROM *", type: "date", placeholder: "04/10/2026" },
      { id: "dateUntil", label: "UNTIL *", type: "date", placeholder: "04/11/2026" },
      { id: "incidentTypes", label: "INCIDENT TYPES *", type: "select", placeholder: "All types" },
      { id: "usersInvolved", label: "USERS INVOLVED *", type: "select", placeholder: "All clients" },
      { id: "columns", label: "SHOW COLUMNS", type: "multiselect", placeholder: "Click here to add more..." },
    ],
    columns: ["DISPLAY FROM", "DISPLAY UNTIL", "ENTRY OCCURRED", "INCIDENT TYPE", "CARERS INVOLVED", "CLIENTS INVOLVED", "DIARY ENTRY", "DIARY LINK"],
    data: [
      {
        displayFrom: "30/03/2026",
        displayUntil: "12/04/2026",
        entryOccurred: "30/03/2026",
        incidentType: "Note",
        carersInvolved: "",
        clientsInvolved: "Tania JAVEED",
        diaryEntry: "school holiday week",
        diaryLink: "Edit entry",
      },
      {
        displayFrom: "06/04/2026",
        displayUntil: "12/04/2026",
        entryOccurred: "06/04/2026",
        incidentType: "Note",
        carersInvolved: "",
        clientsInvolved: "Nathan Oladoyinbo",
        diaryEntry: "school holiday week",
        diaryLink: "Edit entry",
      },
    ],
  },
};
