// Group 2 — Clinical & Medical
// Sources: Batch 1 §1-§7, §10; Batch 2 §9-§12; Batch 4 §5-§7, §9
//
// Diabetes, Respiratory and Pain appear in both Batch 2 and Batch 4; the merged
// module keeps each question once, taking the fuller wording and adding any
// field the other batch introduces.

export const CLINICAL_MODULES = [
  {
    id: "medical-conditions",
    sources: ["Batch 1 §1"],
    title: "Medical Conditions and Current Health",
    gateway: {
      id: "hasCondition",
      label:
        "Does {name} have any diagnosed, suspected or current medical condition that affects care or requires monitoring?",
      type: "single",
      options: ["Yes", "No", "Unsure / awaiting information"],
      mandatory: true,
      skipOn: ["No"],
      note: "If No, record 'No identified medical condition affecting care' and STOP / SKIP. If Unsure, create a mandatory information-gathering action and do not mark the clinical assessment complete.",
    },
    questions: [
      {
        id: "diagnosedConditions",
        label: "What medical conditions are currently diagnosed?",
        type: "multi",
        mandatory: true,
        options: ["Cardiovascular", "Respiratory", "Neurological", "Endocrine", "Renal", "Gastrointestinal", "Musculoskeletal", "Dermatological", "Cancer", "Infection", "Mental health", "Learning disability", "Dementia", "Other"],
        detailPerOption: "Diagnosis, severity / stage and relevant professional",
      },
      { id: "warningSigns", label: "For each condition, what symptoms or warning signs should staff monitor?", type: "textarea", mandatory: true },
      { id: "recentChanges", label: "Are there any recent changes, deterioration, new symptoms or hospital admissions?", type: "single", options: ["No", "Yes", "Unknown"] },
      {
        id: "observations",
        label: "What clinical observations or monitoring are required?",
        type: "multi",
        options: ["Blood pressure", "Pulse", "Temperature", "Respiratory rate", "Oxygen saturation", "Blood glucose", "Weight", "Fluid balance", "Bowel monitoring", "Urine monitoring", "Pain", "Skin", "Other", "None"],
        detailPerOption: "Frequency, acceptable range, escalation threshold and responsible role",
      },
      { id: "allergies", label: "Does {name} have any allergies or adverse reactions?", type: "single", mandatory: true, options: ["No known allergy", "Yes", "Unknown"], note: "Unknown must be resolved before medication support starts." },
      {
        id: "delegatedTasks",
        label: "Are there clinical tasks requiring delegation, competency sign-off or specialist training?",
        type: "multi",
        options: ["None", "Insulin", "PEG / enteral feeding", "Tracheostomy", "Ventilation", "Suction", "Catheter", "Stoma", "Wound care", "Oxygen", "Rescue medication", "Other"],
        note: "A selected task creates a competency requirement and scheduler warning.",
      },
      { id: "deteriorationContact", label: "What would indicate that {name}'s condition is worsening and who must be contacted?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Clinical deterioration", "Allergy / adverse reaction", "Monitoring failure", "Unmet delegated-healthcare need"],
    careWorkerInstructions: [
      { id: "keyConditions", label: "KEY HEALTH CONDITIONS - concise staff-facing summary", mandatory: true },
      { id: "redFlags", label: "WARNING SIGNS / RED FLAGS - what staff MUST look for", mandatory: true },
      { id: "monitoring", label: "CLINICAL MONITORING - what staff MUST record", mandatory: true },
      { id: "escalation", label: "ESCALATION - who to contact and when" },
    ],
    ecm: [
      { id: "obsCompleted", label: "Were required health observations / monitoring completed?", options: ["Yes", "No", "N/A"], action: "No -> reason + escalation / action" },
      { id: "newSymptom", label: "Was there any new symptom, deterioration or health concern?", options: ["No", "Yes"], action: "Yes -> mandatory narrative + escalation" },
      { id: "instructionsFollowed", label: "Were condition-specific instructions followed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> exception + manager / clinical review" },
    ],
  },

  {
    id: "condition-specific",
    sources: ["Batch 1 §2"],
    title: "Condition-Specific Assessment",
    gateway: {
      id: "needsPathway",
      label: "Does {name} have a condition requiring a dedicated condition-specific care pathway or risk assessment?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If Unsure, create an action for clinical / manager review.",
    },
    questions: [
      {
        id: "pathwayRequired",
        label: "Which condition-specific pathway is required?",
        type: "multi",
        mandatory: true,
        options: ["Diabetes", "COPD", "Asthma", "Heart failure", "Parkinson's", "Dementia", "Stroke", "Multiple sclerosis", "Motor neurone disease", "Renal disease", "Cancer", "Autism", "Learning disability", "Mental health condition", "Other"],
        note: "Each selection opens the matching pathway in Step 10 (Specialist Pathways); multiple concurrent pathways are allowed.",
      },
      { id: "conditionBaseline", label: "What is {name}'s usual baseline for this condition?", type: "textarea", mandatory: true },
      { id: "conditionTriggers", label: "What condition-specific triggers or deterioration signs are known?", type: "textarea", mandatory: true },
      { id: "treatmentPlan", label: "What professional treatment / care plan is in place?", type: "textarea" },
      { id: "equipmentMonitoring", label: "What equipment, medication or monitoring is required?", type: "textarea", mandatory: true },
      { id: "deviationAction", label: "What must staff do if {name}'s condition deviates from baseline?", type: "textarea", mandatory: true },
      { id: "outsideRole", label: "What tasks are outside the care worker's role unless specifically delegated and competency-assessed?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Condition deterioration", "Incorrect intervention", "Delayed escalation", "Competency mismatch"],
    careWorkerInstructions: [
      { id: "csBaseline", label: "CONDITION-SPECIFIC BASELINE" },
      { id: "csMonitor", label: "WHAT STAFF MUST MONITOR", mandatory: true },
      { id: "csDo", label: "WHAT STAFF MUST DO", mandatory: true },
      { id: "csNotDo", label: "WHAT STAFF MUST NOT DO / LIMITS OF ROLE", mandatory: true },
    ],
    ecm: [
      { id: "csBaselineMet", label: "Was {name} at their usual condition-specific baseline?", options: ["Yes", "No", "Unsure"], action: "No / Unsure -> record signs + escalate" },
      { id: "csTasksCompleted", label: "Were prescribed condition-specific tasks completed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> exception" },
      { id: "csEscalation", label: "Was specialist escalation required?", options: ["No", "Yes"], action: "Yes -> record who, when, outcome" },
    ],
  },

  {
    id: "medication-support",
    sources: ["Batch 1 §3"],
    title: "Medication Support",
    gateway: {
      id: "takesMedication",
      label: "Does {name} take medication or require any medication-related support from the service?",
      type: "single",
      options: ["Yes", "No", "Unknown"],
      mandatory: true,
      skipOn: ["No"],
      note: "Unknown must create a medication reconciliation action before medication assistance is provided.",
    },
    questions: [
      {
        id: "supportLevel",
        label: "What level of medication support is required?",
        type: "single",
        mandatory: true,
        options: ["Independent / self-administered", "Prompt / remind", "Assist", "Administer", "Specialist / delegated task", "Mixed levels"],
        note: "Use task-level mapping; do not infer administration authority from diagnosis alone.",
      },
      {
        id: "marAvailable",
        label: "Is a current medication list / MAR / eMAR available and reconciled?",
        type: "single",
        mandatory: true,
        options: ["Yes", "No", "Partly", "Awaiting"],
        note: "No / Partly / Awaiting creates a mandatory reconciliation action.",
      },
      { id: "prnPrescribed", label: "Are any PRN medicines prescribed?", type: "single", options: ["No", "Yes"], note: "Yes captures indication, minimum interval, maximum dose, when to escalate and outcome recording." },
      {
        id: "highRiskMedicines",
        label: "Are there controlled drugs, anticoagulants, insulin, rescue medicines or other high-risk medicines?",
        type: "multi",
        options: ["None", "Controlled drug", "Anticoagulant", "Insulin", "Opioid", "Antiepileptic rescue medicine", "Oxygen", "Other"],
        note: "Selected items create a high-risk medicine flag and competency / monitoring requirements.",
      },
      {
        id: "formulationIssues",
        label: "Are there swallowing, crushing, covert administration or formulation issues?",
        type: "multi",
        options: ["None", "Dysphagia", "Liquid formulation", "Crushing", "Covert administration", "PEG / enteral", "Other"],
        note: "Any selected item requires authorised professional instructions.",
      },
      { id: "storage", label: "Where and how is medication stored?", type: "textarea", mandatory: true },
      { id: "repeatPrescriptions", label: "Who orders, collects and manages repeat prescriptions?", type: "textarea", mandatory: true },
      { id: "refusalAction", label: "What should staff do after a refusal, omission, error, adverse reaction or stock problem?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Medication omission", "Medication error", "Adverse reaction", "Storage / access", "PRN / high-risk medicine"],
    careWorkerInstructions: [
      { id: "medSupportLevel", label: "MEDICATION SUPPORT LEVEL" },
      { id: "highRiskPrn", label: "HIGH-RISK / PRN INSTRUCTIONS" },
      { id: "medStorage", label: "STORAGE / ACCESS" },
      { id: "medError", label: "REFUSAL, OMISSION OR ERROR - staff MUST", mandatory: true },
    ],
    ecm: [
      { id: "medDelivered", label: "Was all scheduled medication support delivered as authorised?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> mandatory exception + medication workflow" },
      { id: "medRefused", label: "Was medication refused, omitted, unavailable or given late?", options: ["No", "Yes"], action: "Yes -> reason + escalation" },
      { id: "medAdverse", label: "Any adverse reaction or medication concern?", options: ["No", "Yes"], action: "Yes -> urgent clinical / manager escalation" },
    ],
  },

  {
    id: "dysphagia",
    sources: ["Batch 1 §4"],
    title: "Dysphagia, Swallowing and Choking Risk",
    gateway: {
      id: "hasDysphagia",
      label:
        "Does {name} have diagnosed or suspected dysphagia, swallowing difficulty, recurrent choking / coughing with food or drink, or an aspiration risk?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If Yes or Unsure, continue. Unsure should create a referral / clinical review action where indicated.",
    },
    questions: [
      {
        id: "swallowingSigns",
        label: "What signs of swallowing difficulty are present?",
        type: "multi",
        mandatory: true,
        options: ["Coughing during / after meals", "Choking episodes", "Wet / gurgly voice", "Food pocketing", "Prolonged mealtimes", "Drooling", "Pain / difficulty swallowing", "Recurrent chest infection", "Weight loss", "Dehydration", "Other"],
      },
      {
        id: "saltAssessed",
        label: "Has a Speech and Language Therapist (SALT) or other competent clinician assessed swallowing?",
        type: "single",
        mandatory: true,
        options: ["Yes - current plan available", "Yes - plan unavailable", "No", "Awaiting assessment"],
        note: "If plan unavailable / No / Awaiting and risk is present, create mandatory escalation before staff alter food or fluid texture.",
      },
      {
        id: "foodTexture",
        label: "What food texture is prescribed / recommended?",
        type: "single",
        mandatory: true,
        options: ["Normal", "Soft / bite-sized", "Minced / moist", "Pureed", "Other professionally specified", "Unknown"],
        note: "Record the exact professional instruction; do not allow staff-created texture changes.",
      },
      {
        id: "fluidConsistency",
        label: "What fluid consistency is prescribed / recommended?",
        type: "single",
        mandatory: true,
        options: ["Thin", "Slightly thick", "Mildly thick", "Moderately thick", "Extremely thick", "Other professionally specified", "Unknown"],
        note: "Record the exact professional instruction and thickener preparation where applicable.",
      },
      { id: "positioning", label: "What positioning is required for eating / drinking and for how long afterwards?", type: "textarea", mandatory: true },
      {
        id: "supervisionLevel",
        label: "What level of supervision / assistance is required at meals and drinks?",
        type: "single",
        mandatory: true,
        options: ["Independent", "Prompting", "Intermittent supervision", "Continuous supervision", "Direct assistance", "1:1 specialist support"],
      },
      { id: "utensils", label: "Are there specific utensils, pacing, bite / sip size or feeding techniques?", type: "textarea" },
      { id: "chokingActions", label: "What are the choking / aspiration warning signs and emergency actions?", type: "textarea", mandatory: true },
      { id: "acknowledgedRisk", label: "Does {name} choose to eat / drink in a way that carries acknowledged risk?", type: "single", options: ["No", "Yes", "Not known"], note: "Yes must link to capacity / consent, professional discussion, documented plan and agreed risk management." },
    ],
    riskDomains: ["Choking", "Aspiration", "Malnutrition", "Dehydration", "Incorrect food / fluid consistency"],
    careWorkerInstructions: [
      { id: "saltPlan", label: "SWALLOWING STATUS / SALT PLAN" },
      { id: "textureFluid", label: "FOOD TEXTURE AND FLUID CONSISTENCY - staff MUST follow", mandatory: true },
      { id: "positioningPacing", label: "POSITIONING / SUPERVISION / PACING" },
      { id: "chokingEmergency", label: "CHOKING OR ASPIRATION - emergency instructions" },
    ],
    ecm: [
      { id: "textureProvided", label: "Was the prescribed food texture / fluid consistency provided?", options: ["Yes", "No", "N/A"], action: "No -> immediate exception + safety escalation" },
      { id: "positioningMaintained", label: "Was required positioning / supervision maintained?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> reason + action" },
      { id: "aspirationSigns", label: "Any coughing, choking, wet voice, distress or suspected aspiration?", options: ["No", "Yes"], action: "Yes -> mandatory incident / clinical escalation" },
    ],
  },

  {
    id: "nutrition-hydration",
    sources: ["Batch 1 §5"],
    title: "Nutrition, Hydration and MUST Screening",
    gateway: {
      id: "hasNutritionConcern",
      label:
        "Does {name} have any nutrition, hydration, weight, appetite or malnutrition concern, or require support to eat / drink?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If No, record basic food preferences elsewhere and skip the detailed nutrition-risk questions.",
    },
    questions: [
      {
        id: "eatingDrinkingSupport",
        label: "What support is required with eating and drinking?",
        type: "multi",
        mandatory: true,
        options: ["Meal planning", "Shopping", "Meal preparation", "Prompting", "Cutting food", "Feeding assistance", "Drinks preparation", "Fluid prompting", "Monitoring intake", "Special diet", "Supplements", "Other"],
      },
      {
        id: "screeningTool",
        label: "Has a recognised malnutrition screening tool (for example MUST) been completed?",
        type: "single",
        options: ["Yes", "No", "Not applicable", "Awaiting professional input"],
        note: "If Yes, record tool name, score, date and action. The app may calculate only where the organisation has formally adopted and validated the tool workflow.",
      },
      { id: "currentWeight", label: "Current weight (kg)", type: "number" },
      { id: "weightDate", label: "Date weight measured", type: "date" },
      {
        id: "unplannedWeightLoss",
        label: "Has there been unplanned weight loss?",
        type: "single",
        options: ["No", "Yes", "Unknown"],
        note: "Yes opens amount, timeframe, percentage if known and professional action.",
      },
      {
        id: "dietaryRequirements",
        label: "What dietary requirements apply?",
        type: "multi",
        options: ["Standard", "Diabetic", "Low salt", "Fortified / high calorie", "Vegetarian", "Vegan", "Halal", "Kosher", "Allergy exclusion", "Renal", "Texture modified", "Other"],
      },
      {
        id: "fluidTarget",
        label: "Is there a prescribed fluid target or restriction?",
        type: "single",
        options: ["No", "Yes - target", "Yes - restriction", "Unknown"],
        note: "Yes opens exact volume, source / professional and monitoring instructions.",
      },
      { id: "deteriorationSigns", label: "What signs of dehydration or nutritional deterioration should staff monitor?", type: "textarea", mandatory: true },
      { id: "escalation", label: "When must intake, weight or concerns be escalated and to whom?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Malnutrition", "Dehydration", "Weight loss", "Dietary / allergy error", "Inadequate intake"],
    careWorkerInstructions: [
      { id: "nutritionSupport", label: "NUTRITION / HYDRATION SUPPORT" },
      { id: "dietFluid", label: "DIET / FLUID REQUIREMENTS" },
      { id: "intakeMonitoring", label: "INTAKE OR WEIGHT MONITORING" },
      { id: "escalationTriggers", label: "ESCALATION TRIGGERS" },
    ],
    ecm: [
      { id: "supportProvided", label: "Was required food / drink support provided?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> reason" },
      { id: "monitoringCompleted", label: "Was required intake monitoring completed?", options: ["Yes", "No", "N/A"], action: "No -> exception" },
      { id: "intakeConcern", label: "Was poor intake, dehydration sign or appetite change identified?", options: ["No", "Yes"], action: "Yes -> escalation / action" },
    ],
  },

  {
    id: "skin-integrity",
    sources: ["Batch 1 §6"],
    title: "Waterlow, Skin Integrity and Pressure Ulcer Assessment",
    gateway: {
      id: "hasSkinRisk",
      label:
        "Is {name} at risk of skin damage or pressure ulcer, immobile or less mobile, incontinent, nutritionally compromised, or do they currently have a wound or pressure ulcer?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If Yes or Unsure, continue and consider a professional skin / pressure review.",
    },
    questions: [
      {
        id: "scoringTool",
        label: "Is a Waterlow or other approved pressure-ulcer risk score used by the organisation for this person?",
        type: "single",
        mandatory: true,
        options: ["Waterlow", "Other approved tool", "No formal score required", "Awaiting assessment"],
        note: "If Waterlow is selected, open the validated Waterlow scoring module. Do not change scoring rules without clinical governance approval.",
      },
      { id: "scoreValue", label: "Current Waterlow / approved tool score", type: "number", note: "Auto-calculate only from validated scoring logic; retain individual factor answers and score version / date." },
      {
        id: "riskCategory",
        label: "Current overall pressure-ulcer risk category",
        type: "single",
        mandatory: true,
        options: ["Not currently at risk", "At risk", "High risk", "Very high risk", "Professional classification"],
      },
      {
        id: "existingDamage",
        label: "Is there any existing pressure damage or wound?",
        type: "single",
        mandatory: true,
        options: ["No", "Yes", "Suspected"],
        note: "Yes / Suspected opens body-map location, category or stage only if professionally identified, wound plan, professional contact, and photographs only where policy and consent permit.",
      },
      { id: "damageLocation", label: "Where is skin damage located?", type: "bodymap" },
      {
        id: "pressureEquipment",
        label: "What pressure-relieving equipment is in place?",
        type: "multi",
        options: ["None", "Pressure-relieving mattress", "Cushion", "Heel protection", "Repositioning aid", "Profiling bed", "Other"],
        note: "Record make / type where relevant, servicing status and instructions.",
      },
      { id: "repositioningPlan", label: "What repositioning plan is prescribed or agreed?", type: "textarea", mandatory: true },
      { id: "skinChecks", label: "What skin checks are required and how frequently?", type: "textarea", mandatory: true },
      {
        id: "contributingFactors",
        label: "Are moisture, continence, nutrition, friction / shear or mobility factors contributing to risk?",
        type: "multi",
        options: ["Moisture / incontinence", "Poor nutrition", "Reduced mobility", "Friction / shear", "Sensory loss", "Poor circulation", "Other", "None"],
      },
      { id: "immediateEscalation", label: "What changes require immediate escalation?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Pressure damage", "Wound deterioration", "Failure to reposition", "Equipment failure", "Moisture-associated skin damage"],
    careWorkerInstructions: [
      { id: "riskLevel", label: "PRESSURE / SKIN RISK LEVEL" },
      { id: "repositioning", label: "REPOSITIONING - staff MUST", mandatory: true },
      { id: "checksEquipment", label: "SKIN CHECKS / EQUIPMENT" },
      { id: "newDamage", label: "NEW REDNESS, BREAKDOWN OR WOUND CHANGE - staff MUST", mandatory: true },
    ],
    ecm: [
      { id: "repositioningDone", label: "Was the required repositioning completed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> reason + escalation based on risk" },
      { id: "skinInspection", label: "Was required skin inspection completed?", options: ["Yes", "No", "N/A"], action: "No -> exception" },
      { id: "newSkinChange", label: "Any new redness, blistering, broken skin or wound deterioration?", options: ["No", "Yes"], action: "Yes -> mandatory body-map / narrative + clinical escalation" },
    ],
  },

  {
    id: "seizures-epilepsy",
    sources: ["Batch 1 §7"],
    title: "Seizures and Epilepsy",
    gateway: {
      id: "hasSeizures",
      label: "Does {name} have epilepsy, a history of seizures, unexplained episodes, or a seizure management plan?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If Unsure, continue basic screening and create an information / clinical review action.",
    },
    questions: [
      {
        id: "seizureTypes",
        label: "What seizure type(s) does {name} experience?",
        type: "multi",
        mandatory: true,
        options: ["Generalised convulsive", "Focal aware", "Focal impaired awareness", "Absence", "Atonic / drop", "Myoclonic", "Unknown / unclassified", "Other"],
      },
      { id: "usualPresentation", label: "What does {name}'s usual seizure look like from start to recovery?", type: "textarea", mandatory: true },
      { id: "frequency", label: "How often do seizures occur?", type: "text", mandatory: true },
      { id: "mostRecent", label: "Date of most recent seizure", type: "date", mandatory: true },
      {
        id: "triggers",
        label: "What known triggers or warning signs / aura exist?",
        type: "multi",
        options: ["Missed medication", "Illness / fever", "Sleep deprivation", "Stress", "Alcohol / substance", "Flashing light", "Menstrual / hormonal", "Unknown", "Other"],
      },
      {
        id: "managementPlan",
        label: "Is there an individualised seizure / emergency management plan?",
        type: "single",
        mandatory: true,
        options: ["Yes - available", "Yes - not available", "No", "Awaiting"],
        note: "If not available and seizures are present, create an urgent action to obtain or confirm the plan.",
      },
      {
        id: "rescueMedication",
        label: "Is rescue medication prescribed?",
        type: "single",
        mandatory: true,
        options: ["No", "Yes", "Unknown"],
        note: "Yes opens medicine, route, dose, when to give, repeat / max dose, competency requirement and when to call 999.",
      },
      { id: "emergencyThreshold", label: "What seizure duration or frequency requires emergency services or clinical escalation?", type: "textarea", mandatory: true },
      { id: "firstAid", label: "What first-aid, positioning, observation and post-seizure support are required?", type: "textarea", mandatory: true },
      {
        id: "postSeizureRecording",
        label: "What must staff record after a seizure?",
        type: "multi",
        mandatory: true,
        options: ["Start time", "End time", "Observed features", "Possible trigger", "Injury", "Rescue medicine", "Recovery time", "Post-ictal state", "Escalation", "Other"],
      },
    ],
    riskDomains: ["Prolonged seizure / status", "Injury", "Rescue-medication delay / error", "Aspiration", "Post-seizure deterioration"],
    careWorkerInstructions: [
      { id: "usualSeizure", label: "USUAL SEIZURE PRESENTATION" },
      { id: "firstAidActions", label: "FIRST AID / SAFETY ACTIONS" },
      { id: "rescueInstructions", label: "RESCUE MEDICATION - exact authorised instructions" },
      { id: "when999", label: "WHEN TO CALL 999 / ESCALATE" },
    ],
    ecm: [
      { id: "seizureOccurred", label: "Did a seizure or suspected seizure occur?", options: ["No", "Yes"], action: "Yes -> seizure record + incident / clinical workflow" },
      { id: "rescueGiven", label: "If rescue medication was required, was it given according to the plan?", options: ["Yes", "No", "N/A"], action: "No -> urgent escalation" },
      { id: "postSeizureSupport", label: "Was post-seizure monitoring / recovery support completed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> exception" },
    ],
  },

  {
    id: "diabetes",
    sources: ["Batch 2 §11", "Batch 4 §6"],
    title: "Diabetes and Blood Glucose Support",
    intro:
      "Batch 2 and Batch 4 both assess diabetes; the questions are merged here so each is asked once.",
    gateway: {
      id: "hasDiabetes",
      label: "Does {name} have diabetes, impaired glucose regulation or require diabetes-related support?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
    },
    questions: [
      { id: "diabetesType", label: "What type of diabetes does {name} have?", type: "single", mandatory: true, options: ["Type 1", "Type 2", "Other / secondary", "Unknown"] },
      {
        id: "management",
        label: "How is {name}'s diabetes managed?",
        type: "multi",
        mandatory: true,
        options: ["Diet", "Tablets / non-insulin medicine", "Insulin", "Continuous glucose monitor", "Finger-prick monitoring", "Insulin pump", "Other"],
      },
      { id: "independentTasks", label: "What diabetes tasks can {name} manage independently?", type: "textarea", mandatory: true },
      {
        id: "staffSupportLevel",
        label: "Does {name} require staff support with blood glucose monitoring or insulin?",
        type: "single",
        mandatory: true,
        options: ["No", "Prompting", "Assist", "Staff task under competency / delegation", "Other"],
      },
      { id: "monitoringWhoHowOften", label: "Who performs blood glucose monitoring and how often?", type: "textarea", mandatory: true },
      { id: "targetRanges", label: "What are {name}'s usual glucose target / action ranges if professionally specified?", type: "textarea" },
      { id: "hypoSigns", label: "What are {name}'s typical signs of hypoglycaemia?", type: "textarea", mandatory: true },
      { id: "hypoTreatmentPlan", label: "What is {name}'s individual hypoglycaemia treatment plan?", type: "textarea", mandatory: true },
      { id: "hyperSigns", label: "What are {name}'s typical signs of hyperglycaemia or illness, and what requires escalation?", type: "textarea", mandatory: true },
      { id: "authorisedResponse", label: "What is the authorised response to hypo / hyperglycaemia and when should staff seek urgent help?", type: "textarea", mandatory: true },
      {
        id: "additionalConsiderations",
        label: "Are foot, skin, nutrition or sick-day considerations relevant?",
        type: "multi",
        options: ["Foot care", "Skin / wounds", "Meal timing", "Sick-day plan", "Hydration", "Other", "None"],
      },
    ],
    riskDomains: ["Hypoglycaemia", "Hyperglycaemia", "Insulin / monitoring error", "Monitoring failure", "Diabetic foot / skin complication"],
    careWorkerInstructions: [
      { id: "baseline", label: "DIABETES MANAGEMENT / {name}'S BASELINE", mandatory: true },
      { id: "glucoseSupport", label: "GLUCOSE / INSULIN SUPPORT AND THRESHOLDS", mandatory: true },
      { id: "hypoHyperSigns", label: "HYPO / HYPER SIGNS AND ACTION", mandatory: true },
      { id: "emergency", label: "DIABETES EMERGENCY - staff MUST", mandatory: true },
      { id: "roleLimits", label: "INSULIN / MEDICATION LIMITS OF ROLE" },
    ],
    ecm: [
      { id: "supportCompleted", label: "Was required diabetes support completed?", options: ["Yes", "No", "N/A"], action: "No -> medication / clinical exception" },
      { id: "outsideRange", label: "Was glucose outside {name}'s agreed action range or were symptoms present?", options: ["No", "Yes", "N/A"], action: "Yes -> follow diabetes plan / escalate" },
      { id: "newConcern", label: "Was any new foot, skin, eating or illness concern identified?", options: ["No", "Yes"], action: "Yes -> clinical review" },
    ],
  },

  {
    id: "respiratory-oxygen",
    sources: ["Batch 2 §9", "Batch 2 §10", "Batch 4 §5"],
    title: "Respiratory Health, Oxygen and Breathing Support",
    intro:
      "Merges respiratory health with oxygen therapy and safety, which Batch 2 splits across two sections and Batch 4 combines.",
    gateway: {
      id: "hasRespiratoryNeed",
      label:
        "Does {name} have a respiratory condition, breathlessness, recurrent chest infection, or need respiratory monitoring or support?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
    },
    questions: [
      {
        id: "conditions",
        label: "Which respiratory conditions affect {name}?",
        type: "multi",
        mandatory: true,
        options: ["COPD", "Asthma", "Bronchiectasis", "Pulmonary fibrosis", "Sleep apnoea", "Neuromuscular respiratory weakness", "Recurrent infection", "Other"],
      },
      { id: "baseline", label: "What is {name}'s usual respiratory / breathing baseline?", type: "textarea", mandatory: true },
      {
        id: "triggers",
        label: "What usually triggers breathlessness or respiratory deterioration?",
        type: "multi",
        options: ["Exertion", "Infection", "Position", "Anxiety", "Allergen", "Weather", "Secretions", "Other", "Unknown"],
      },
      {
        id: "equipment",
        label: "What respiratory equipment or treatment is used?",
        type: "multi",
        mandatory: true,
        options: ["Inhaler", "Nebuliser", "Spacer", "CPAP", "BiPAP / NIV", "Oxygen", "Suction", "Tracheostomy", "Ventilator", "Other", "None"],
      },
      { id: "observations", label: "What respiratory observations are required and what professional thresholds apply?", type: "textarea" },
      { id: "equipmentInstructions", label: "What inhaler, nebuliser, CPAP / BiPAP or ventilation support is required?", type: "textarea" },
      {
        id: "oxygenPrescribed",
        label: "Is oxygen prescribed for use at home or in the community?",
        type: "single",
        mandatory: true,
        options: ["Yes", "No", "Unsure"],
        note: "If Yes, the oxygen questions below become mandatory and current prescribed oxygen instructions are required.",
      },
      {
        id: "oxygenSystem",
        label: "What oxygen delivery system does {name} use?",
        type: "multi",
        options: ["Concentrator", "Cylinder", "Portable concentrator", "Liquid oxygen", "Other"],
      },
      {
        id: "oxygenFlowRate",
        label: "What is the prescribed flow rate / dose, and when should oxygen be used?",
        type: "textarea",
        note: "Staff must not alter the flow rate unless specifically authorised in a clinical plan.",
      },
      {
        id: "oxygenInterface",
        label: "What delivery interface is used?",
        type: "single",
        options: ["Nasal cannula", "Mask", "Tracheostomy interface", "Other"],
      },
      {
        id: "oxygenIndependence",
        label: "Can {name} manage oxygen independently?",
        type: "single",
        options: ["Yes", "With prompting", "With assistance", "No"],
      },
      {
        id: "fireRisks",
        label: "Are smoking, naked flames, aerosols, petroleum-based products or heat sources a risk?",
        type: "multi",
        options: ["None identified", "Smoking", "Naked flame", "Gas cooking / fire", "Candles", "Aerosols", "Petroleum-based product", "Other"],
      },
      {
        id: "oxygenSafetyPlan",
        label: "Is an oxygen / fire safety plan available?",
        type: "single",
        options: ["Yes", "No", "Awaiting"],
        note: "No / Awaiting creates a mandatory fire-safety action.",
      },
      { id: "equipmentFailure", label: "What should staff do if oxygen equipment fails or supply runs low?", type: "textarea" },
      { id: "warningSigns", label: "What are {name}'s early warning signs of respiratory deterioration?", type: "textarea", mandatory: true },
      { id: "redFlags", label: "What red flags require urgent clinical help or 999, including symptoms that persist despite oxygen?", type: "textarea", mandatory: true },
      { id: "positioningStrategies", label: "What positioning, pacing or breathing strategies help {name}?", type: "textarea" },
    ],
    riskDomains: ["Acute respiratory deterioration", "Hypoxia", "Delayed escalation", "Equipment / treatment failure", "Chest infection", "Fire / explosion (oxygen)", "Incorrect oxygen dose", "Supply / equipment failure"],
    careWorkerInstructions: [
      { id: "respiratoryBaseline", label: "{name}'S RESPIRATORY BASELINE", mandatory: true },
      { id: "equipmentSupport", label: "EQUIPMENT / TREATMENT SUPPORT AND MONITORING", mandatory: true },
      { id: "oxygenRegimen", label: "PRESCRIBED OXYGEN REGIMEN" },
      { id: "oxygenFireSafety", label: "OXYGEN FIRE-SAFETY RULES" },
      { id: "backupArrangement", label: "EQUIPMENT / BACK-UP ARRANGEMENT" },
      { id: "earlyWarning", label: "EARLY WARNING SIGNS / RED FLAGS", mandatory: true },
      { id: "emergency", label: "RESPIRATORY OR OXYGEN EMERGENCY - staff MUST", mandatory: true },
    ],
    ecm: [
      { id: "atBaseline", label: "Was {name} at their usual respiratory baseline?", options: ["Yes", "No", "N/A"], action: "No -> record signs + escalation" },
      { id: "treatmentCompleted", label: "Was respiratory treatment / equipment support completed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> exception" },
      { id: "oxygenAsPrescribed", label: "Was oxygen used exactly as prescribed where required?", options: ["Yes", "No", "N/A"], action: "No -> urgent exception" },
      { id: "fireSafetyMaintained", label: "Were oxygen fire-safety controls maintained?", options: ["Yes", "No", "N/A"], action: "No -> immediate safety action" },
      { id: "newSymptoms", label: "Was new or worsening breathlessness, cough, sputum or distress identified?", options: ["No", "Yes"], action: "Yes -> clinical escalation" },
    ],
  },

  {
    id: "pain-management",
    sources: ["Batch 2 §12", "Batch 4 §7"],
    title: "Pain Assessment and Symptom Management",
    intro: "Batch 2 and Batch 4 both assess pain; merged so each question is asked once.",
    gateway: {
      id: "hasPain",
      label: "Does {name} experience acute, chronic or recurrent pain, or have difficulty communicating pain?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
    },
    questions: [
      { id: "painLocation", label: "Where does {name} usually experience pain?", type: "bodymap", mandatory: true },
      {
        id: "painDescription",
        label: "How does {name} describe or communicate the pain?",
        type: "multi",
        mandatory: true,
        options: ["Aching", "Sharp", "Burning", "Throbbing", "Cramping", "Neuropathic / tingling", "Unable to describe", "Other"],
      },
      {
        id: "severityMethod",
        label: "How should {name}'s pain severity be assessed?",
        type: "single",
        mandatory: true,
        options: ["0-10 verbal scale", "Visual scale", "Behavioural / non-verbal observation", "Individual pain tool", "Other"],
      },
      { id: "baseline", label: "What is {name}'s usual / baseline pain level?", type: "text", mandatory: true },
      {
        id: "worseningTriggers",
        label: "What commonly triggers or worsens pain?",
        type: "multi",
        options: ["Movement / transfers", "Personal care", "Position", "Time of day", "Weather", "Activity", "Anxiety", "Other", "Unknown"],
      },
      {
        id: "reliefMeasures",
        label: "What pain medicines or non-drug measures are used?",
        type: "multi",
        options: ["Regular analgesia", "PRN analgesia", "Positioning", "Heat / cold if authorised", "Massage if appropriate", "Rest", "Movement", "Other"],
      },
      { id: "betterWorse", label: "What makes {name}'s pain better or worse?", type: "textarea", mandatory: true },
      {
        id: "prnPrescribed",
        label: "Are PRN analgesics prescribed, and are outcome checks required?",
        type: "single",
        options: ["No", "Yes - outcome check required", "Yes - no outcome check specified", "Unknown"],
      },
      { id: "nonVerbalSigns", label: "How does {name} show pain if they cannot reliably describe it?", type: "textarea", mandatory: true },
      { id: "escalation", label: "What pain change or associated symptom requires clinical escalation?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Uncontrolled pain", "Unrecognised pain", "Delayed recognition", "Analgesia-related risk", "Acute pain deterioration", "Reduced mobility / intake / sleep"],
    careWorkerInstructions: [
      { id: "painBaseline", label: "{name}'S PAIN BASELINE / HOW THEY SHOW PAIN", mandatory: true },
      { id: "reliefSupport", label: "PAIN RELIEF MEASURES", mandatory: true },
      { id: "prnMonitoring", label: "PRN / OUTCOME MONITORING INSTRUCTIONS" },
      { id: "redFlags", label: "PAIN RED FLAGS - staff MUST", mandatory: true },
    ],
    ecm: [
      { id: "painDuringVisit", label: "Was {name} experiencing pain during this visit?", options: ["No", "Yes"], action: "Yes -> record severity / action" },
      { id: "reliefHelped", label: "Did agreed pain-relief measures help?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> review / escalate" },
      { id: "newPain", label: "Was there new, severe or unexplained pain?", options: ["No", "Yes"], action: "Yes -> clinical escalation" },
    ],
  },

  {
    id: "infection-prevention",
    sources: ["Batch 4 §9"],
    title: "Infection Prevention, Communicable Illness and PPE",
    gateway: {
      id: "hasInfectionRisk",
      label:
        "Does {name} have an infection, infection risk, wound or device-related infection concern, or a specific infection-prevention requirement affecting care?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If No, universal infection-prevention practice still applies; only the person-specific questions are skipped.",
    },
    questions: [
      {
        id: "specificRisks",
        label: "Which person-specific infection risks apply?",
        type: "multi",
        mandatory: true,
        options: ["Current infection", "Recurrent UTI", "Respiratory infection risk", "Wound", "Catheter", "Stoma", "MRSA / MDRO history", "C. difficile history", "Blood-borne virus", "Immunosuppression", "Other"],
      },
      {
        id: "precautions",
        label: "Are any additional precautions currently required?",
        type: "multi",
        options: ["Standard precautions only", "Gloves", "Apron / gown", "Mask", "Eye protection", "Isolation / limited contact instruction", "Enhanced cleaning", "Dedicated equipment", "Laundry instruction", "Waste instruction", "Other"],
      },
      { id: "monitorSigns", label: "What symptoms or signs should staff monitor?", type: "textarea", mandatory: true },
      { id: "ppeSequence", label: "What hand-hygiene or PPE sequence is required for specific care tasks?", type: "textarea" },
      { id: "laundryWaste", label: "How should contaminated laundry, waste or equipment be handled?", type: "textarea" },
      {
        id: "outbreakInstructions",
        label: "Are there current outbreak, public-health or professional instructions?",
        type: "single",
        options: ["No", "Yes", "Awaiting information"],
      },
      {
        id: "suspectedInfectionAction",
        label:
          "What should staff do if they identify fever, new respiratory symptoms, diarrhoea or vomiting, wound infection signs, or another suspected infection?",
        type: "textarea",
        mandatory: true,
      },
    ],
    riskDomains: ["Transmission to {name}", "Transmission to staff / others", "Device / wound infection", "Incorrect PPE / IPC practice", "Delayed recognition / escalation"],
    careWorkerInstructions: [
      { id: "specificRisks", label: "PERSON-SPECIFIC INFECTION RISKS", mandatory: true },
      { id: "ppeRequired", label: "PPE / PRECAUTIONS REQUIRED", mandatory: true },
      { id: "cleaningInstructions", label: "CLEANING / LAUNDRY / WASTE INSTRUCTIONS" },
      { id: "warningSigns", label: "INFECTION WARNING SIGNS", mandatory: true },
      { id: "escalationOutbreak", label: "ESCALATION / OUTBREAK INSTRUCTIONS", mandatory: true },
    ],
    ecm: [
      { id: "precautionsFollowed", label: "Were required infection-prevention precautions / PPE followed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> IPC exception" },
      { id: "newSigns", label: "Were any new infection signs identified?", options: ["No", "Yes"], action: "Yes -> mandatory escalation" },
      { id: "cleaningCompleted", label: "Was required cleaning / waste / laundry procedure completed?", options: ["Yes", "No", "N/A"], action: "No -> corrective action" },
    ],
  },

  {
    id: "end-of-life",
    sources: ["Batch 1 §10"],
    title: "End of Life and Palliative Care",
    gateway: {
      id: "isPalliative",
      label:
        "Is {name} receiving palliative care, approaching end of life, or subject to an advance / end-of-life care plan?",
      type: "single",
      options: ["Yes", "No", "Unsure"],
      mandatory: true,
      skipOn: ["No"],
      note: "If Yes or Unsure, continue sensitively and create an information action where documents or wishes are unclear.",
    },
    questions: [
      { id: "currentStatus", label: "What is {name}'s current palliative / end-of-life status and who confirmed it?", type: "textarea", mandatory: true },
      {
        id: "advanceDocuments",
        label: "Is there an advance care plan, ReSPECT form, DNACPR decision, advance decision or other relevant document?",
        type: "multi",
        mandatory: true,
        options: ["Advance care plan", "ReSPECT", "DNACPR", "Advance decision to refuse treatment", "None known", "Other"],
        note: "Record location, date, version and who verified the document. Do not infer meaning beyond the actual document.",
      },
      { id: "whatMatters", label: "What matters most to {name} at this stage?", type: "textarea", mandatory: true },
      { id: "preferredPlace", label: "What is {name}'s preferred place of care and, if known, preferred place of death?", type: "textarea" },
      {
        id: "symptoms",
        label: "What symptoms require monitoring or support?",
        type: "multi",
        mandatory: true,
        options: ["Pain", "Breathlessness", "Nausea / vomiting", "Agitation / anxiety", "Respiratory secretions", "Constipation", "Delirium / confusion", "Skin / pressure care", "Reduced intake", "Other"],
      },
      {
        id: "anticipatoryMedicines",
        label: "Are anticipatory medicines available and who is authorised to administer them?",
        type: "single",
        options: ["No", "Yes", "Unknown"],
        note: "Care workers must not administer outside their competence or authorisation.",
      },
      { id: "deteriorationSigns", label: "What changes indicate that {name} may be deteriorating or entering the last days or hours of life?", type: "textarea", mandatory: true },
      { id: "firstContact", label: "Who should be contacted first if deterioration or death occurs?", type: "textarea", mandatory: true },
      { id: "culturalWishes", label: "What cultural, spiritual, religious, family and after-death wishes must be respected?", type: "textarea", mandatory: true },
    ],
    riskDomains: ["Uncontrolled symptoms", "Failure to follow advance plan", "Delayed escalation", "Unwanted hospital transfer", "Failure to respect wishes"],
    careWorkerInstructions: [
      { id: "whatMattersMost", label: "WHAT MATTERS MOST AT END OF LIFE" },
      { id: "comfortMeasures", label: "SYMPTOM SUPPORT / COMFORT MEASURES" },
      { id: "advancePlanInstructions", label: "ADVANCE PLAN / ReSPECT / DNACPR - staff instructions" },
      { id: "deteriorationContacts", label: "DETERIORATION / DEATH - who to contact and what to do" },
    ],
    ecm: [
      { id: "comfortTasks", label: "Were comfort and symptom-support tasks completed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> urgent review based on need" },
      { id: "newSymptom", label: "Was there any deterioration or new end-of-life symptom?", options: ["No", "Yes"], action: "Yes -> clinical escalation" },
      { id: "wishesFollowed", label: "Were the person's documented wishes / preferences followed?", options: ["Yes", "Partly", "No", "N/A"], action: "Partly / No -> mandatory explanation + manager review" },
    ],
  },
];
